name: next_top_tech
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.2
  chewie: ^1.7.4
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.2.0
  equatable: ^2.0.5
  file_picker: ^6.1.1
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.6
  font_awesome_flutter: ^10.6.0
  get_it: ^7.6.7
  iconly: ^1.0.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  lottie: ^3.0.0
  open_file: ^3.3.2
  path_provider: ^2.1.2
  provider: ^6.1.1
  sentry_flutter: ^7.7.0
  sentry_dio: ^7.7.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.5

  url_launcher: ^6.2.4
  video_thumbnail: ^0.5.3
  youtube_metadata: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.5
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
    - family: Mehran
      fonts:
        - asset: assets/fonts/Mehran.ttf

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icons/app_icon.png'

